### ISSUE TITLE
Unity, DllNotFoundException

### ISSUE THREAD

**Issue by SradnickDev** [nxrighthere/ValveSockets-CSharp#1]
Hi,
Im pretty excited to use this Wrapper but i dont rly know how to start.
I created a new Project, add a Plugins Folder and copied the [GameNetworkingSockets](https://github.com/ValveSoftware/GameNetworkingSockets) into this Folder. Tryed to start and got this Error Message "DllNotFoundException: GameNetworkingSockets".

Any hints on this ?

**Comment by nxrighthere** [comment]
The native library must be placed to the appropriate plugins folder. You can take a look at [how it's done](https://github.com/nxrighthere/ENet-CSharp/releases) with ENet.

**Comment by SradnickDev** [comment]
Yeah, I did it like this Assets/Plugins/x86_64/GameNetworkingSockets
but still DllNotFoundException.

**Comment by nxrighthere** [comment]
Make sure that the folders structure is matched to this:
- ValveSockets
   - Scripts
     - ValveSockets.cs
  - Plugins
    - x86_64
      - GameNetworkingSockets.dll

If it still doesn't work for you, drag and drop files into the comment here.

**Comment by nxrighthere** [comment]
Try this package - [ValveSockets-Windows-x64.zip](https://github.com/nxrighthere/ValveSockets-CSharp/files/2386118/ValveSockets-Windows-x64.zip). It works without any issues on my side.

**Comment by SradnickDev** [comment]
Now I got first this Warning "Plugins: Failed to load 'Assets/ValveSockets/Plugins/x86_64/GameNetworkingSockets.dll' with error 'The specified module was not found.'.
and then the DllNotFoundException.

**Comment by SradnickDev** [comment]
Seems the ddl was complied for 32 instead of 64 ? 

Plugins: Failed to load 'Assets/ValveSockets/Plugins/x86_64/GameNetworkingSockets.dll' with error '%1 is not a valid Win32 application.

**Comment by SradnickDev** [comment]
Could you pls make it 64bit?

**Comment by nxrighthere** [comment]
It's compiled for 64-bit system and works with 64-bit Unity editor.

This error occur if:
- Your OS or Unity editor is 32-bit
- Your OS is lack of some dependencies (you can use [Dependency Walker](http://www.dependencywalker.com) to find which are is missed)
- Downloaded files corrupted/blocked by the antivirus software

**Comment by nxrighthere** [comment]
I've tried to use the native library with Unity editor on my laptop, and it works fine as well as on PC.

**Comment by SradnickDev** [comment]
Mh, Unity Editor is 64bit, OS is Win10 64bit - x64based processor
dependency walker gave me this
![dependencywalker](https://user-images.githubusercontent.com/40965190/45594141-fd8de280-b995-11e8-89f5-23b07dfedd49.gif)

Thanks for your Help, I really appreciate it!

**Comment by nxrighthere** [comment]
Now I see. You need to install the required Microsoft Visual C++ Redistributable (x64) packages. Dependency Walker shows that there's only the x86 version is installed.

**Comment by nxrighthere** [comment]
Everything should look like on this screenshot:
![dependencywalker](https://user-images.githubusercontent.com/8279330/45594434-11e0d800-b9b4-11e8-8cd9-49f5cb9941c0.PNG)

**Comment by SradnickDev** [comment]
I installed the required packages but nothing changed.

**Comment by nxrighthere** [comment]
Show me please a screenshot of what Dependency Walker reports now.

**Comment by nxrighthere** [comment]
The same thing happens when you are using the libraries that you built instead of those that I upload here?

**Comment by SradnickDev** [comment]
Well, i get a bunch of different erros , so i dont try it again with my build..did this the first time..I actually reinstalled everything and try it again to Use ur libraries.If not I am Home in one week and will try it on my PC, atm I only got my surface.

**Comment by nxrighthere** [comment]
I'm closing this for now since everything works fine at my end on two different machines, and users are reporting positive feedback except some problems with the native library itself. If you still have some problems related to this issue, feel free to drop me a message here, and we will try to resolve the problem.
