### ISSUE TITLE
CloseConnection reason value check seems is not sync with native side.

### ISSUE THREAD

**Issue by Levendo** [nxrighthere/ValveSockets-CSharp#10]
Hey,

binding class has below method: 

```
public bool CloseConnection(Connection connection, int reason, string debug, bool enableLinger) {
if (reason > Library.maxCloseReasonValue)
	throw new ArgumentOutOfRangeException("reason");

if (debug.Length > Library.maxCloseMessageLength)
	throw new ArgumentOutOfRangeException("debug");

return Native.SteamAPI_ISteamNetworkingSockets_CloseConnection(nativeSockets, connection, reason, debug, enableLinger);
		}
```

with **maxCloseReasonValue** is set to **999**.
But on native side things are quite different on APICloseConnection api.

```
if ( nReason == 0 )
{
	nReason = k_ESteamNetConnectionEnd_App_Generic;
}
else if ( nReason < k_ESteamNetConnectionEnd_App_Min || nReason > k_ESteamNetConnectionEnd_AppException_Max )
{
	// Use a special value so that we can detect if people have this bug in our analytics
	nReason = k_ESteamNetConnectionEnd_App_Max;
	pszDebug = "Invalid numeric reason code";
}		
```

and steamnetworkingtypes.h tells:

// 1xxx: Application ended the connection in a "usual" manner.
//       E.g.: user intentionally disconnected from the server,
//             gameplay ended normally, etc
**k_ESteamNetConnectionEnd_App_Min = 1000,**
k_ESteamNetConnectionEnd_App_Generic = k_ESteamNetConnectionEnd_App_Min,
// Use codes in this range for "normal" disconnection
**k_ESteamNetConnectionEnd_App_Max = 1999,**
		
// 2xxx: Application ended the connection in some sort of exceptional
//       or unusual manner that might indicate a bug or configuration
//       issue.
// 
**k_ESteamNetConnectionEnd_AppException_Min = 2000,**
k_ESteamNetConnectionEnd_AppException_Generic = k_ESteamNetConnectionEnd_AppException_Min,
// Use codes in this range for "unusual" disconnection
**k_ESteamNetConnectionEnd_AppException_Max = 2999**

which makes the reason code expected between 1000 and 2999. As long as binding class expect below 999, otherwise it will give exception. If you give below 999, you may get "invalid numeric reason code" error on native side. In other words it seems native and binding sides expecting different values.

**Comment by nxrighthere** [comment]
I just removed it, since the native side handles this with debug logging. Thanks.
