### ISSUE TITLE
Changed callback plumbing

### ISSUE THREAD

**Issue by fletcherdvalve** [nxrighthere/ValveSockets-CSharp#11]
FYI, I've changed how callbacks are plumbed, and I'm sure that I just broke this library.  The good news is that now it is possible to use the same mechanism either in Steamworks or the opensource version.  Let me know if anything is unclear.

**Comment by nxrighthere** [comment]
I like this change! It makes interop much cheaper since we don't need to pass a delegate reference to the native side, which is a costly operation.

**Comment by fletcherdvalve** [comment]
👍
