### ISSUE TITLE
Unity Editor crashes when entering play mode for second time

### ISSUE THREAD

**Issue by mnursey** [nxrighthere/ValveSockets-CSharp#14]
Hi,

I'm encountering an issue where the Unity Editor crashes when I enter play mode for the second time.
Error flow:

Press play,
Library initializes (OnAwake).
.. use library (all works fine) ..
Library Deinitialize (OnApplicationQuit)
Exit Playmode
Press Play again... crash...

I'm running on Windows using 1.2 release for both ValveSockets-CSharp and GameNetworkingSockets.

Any other info can I provide you with?

Thanks

**Comment by nxrighthere** [comment]
The native library has [this](https://github.com/ValveSoftware/GameNetworkingSockets/pull/109) fix?

**Comment by nxrighthere** [comment]
Please, recompile the native library using debug build and share a crash dump with log files.

**Comment by mnursey** [comment]
Will do.

Unless I'm terribly wrong I don't think that fix in included in 1.2v or master. I've added that line in my version and trying it now. 
I'll recompile using debug build and share the files tomorrow. 

I'm building the native library using vcpkg then copying the dlls from ...\GameNetworkingSockets\vcpkg\installed\x64-windows\bin into unity. Is this correct?

**Comment by mnursey** [comment]
Adding that fix doesn't work. Unity still crashes.

**Comment by nxrighthere** [comment]
Tell me please your OS and Unity version.

**Comment by mnursey** [comment]
Windows 10 64x, Unity 2019.3.9f1

**Comment by mnursey** [comment]
[Editor.log](https://github.com/nxrighthere/ValveSockets-CSharp/files/5406192/Editor.log)
[error.log](https://github.com/nxrighthere/ValveSockets-CSharp/files/5406193/error.log)

Here are the error logs.

**Comment by mnursey** [comment]
[Crash.zip](https://github.com/nxrighthere/ValveSockets-CSharp/files/5406214/Crash.zip)
Here is the crash dump with logs

**Comment by nxrighthere** [comment]
How `StatusCallback` is declared in your code? If you don't use `NetworkingUtils.SetStatusCallback()` function, the crash occurs?

**Comment by mnursey** [comment]
[MonoPInvokeCallback(typeof(StatusCallback))]
    static void OnClientStatusUpdate(ref StatusInfo info)
    {
        switch (info.connectionInfo.state)
        {
            case Valve.Sockets.ConnectionState.None:
                break;

            case Valve.Sockets.ConnectionState.Connecting:
                break;

            case Valve.Sockets.ConnectionState.Connected:
                Debug.Log(String.Format("Connected to server - ID: {0}, IP: {1}", Instance.connection, info.connectionInfo.address.GetIP()));

                Instance.connected = true;
                Instance.onConnect?.Invoke(Instance.connected);
                break;

            case Valve.Sockets.ConnectionState.ClosedByPeer:

                Instance.onDisconnect?.Invoke();
                Instance.Disconnect();

                Debug.Log(String.Format("Disconnected from server (closed by server) - ID: {0}, IP: {1}", Instance.connection, info.connectionInfo.address.GetIP()));
                break;

            case Valve.Sockets.ConnectionState.ProblemDetectedLocally:

                if(!Instance.connected)
                    Instance.onConnect?.Invoke(Instance.connected);
                else
                    Instance.onDisconnect?.Invoke();

                Instance.Disconnect();

                Debug.Log(String.Format("Disconnected from server (error) - ID: {0}, IP: {1}", Instance.connection, info.connectionInfo.address.GetIP()));
                break;
        }
    }

with

`utils.SetStatusCallback(status);`

**Comment by nxrighthere** [comment]
Please, share how exactly `OnClientStatusUpdate` is assigned, you pass a variable in `utils.SetStatusCallback(status);`.

**Comment by mnursey** [comment]
public class ClientController : MonoBehaviour {
    ...
    private StatusCallback status;
    NetworkingSockets client;
    NetworkingUtils utils;
    ...

    public void ConnectToServer(...) {
        utils = new NetworkingUtils();
        utils.SetDebugCallback(DebugType.Message, debug);

        client = new NetworkingSockets();

        Address address = new Address();

        address.SetAddress(serverIP, serverport);

        connection = client.Connect(ref address);

        status = OnClientStatusUpdate;
        utils.SetStatusCallback(status);
    }

Commenting out the 
`utils.SetStatusCallback(status);`
 removes the issue.

**Comment by nxrighthere** [comment]
It solves the issue if `private StatusCallback status;` is declared as a static variable?

**Comment by mnursey** [comment]
Unfortunately changing it to `private static StatusCallback status;` does not solve the issue.

**Comment by mnursey** [comment]
I was previously using an older version of both the ValveSockets and the native library. I'm not sure which version for either. I wonder why the new versions don't work for me.

**Comment by nxrighthere** [comment]
Because of https://github.com/nxrighthere/ValveSockets-CSharp/issues/11.

@fletcherdvalve What might cause a crash if library initialized/deinitialized multiple times within the same process when it's loaded dynamically (but never unloaded from memory) and `SteamAPI_ISteamNetworkingUtils_SetDebugOutputFunction()` was previously used to set a callback function?

**Comment by nxrighthere** [comment]
@mnursey If after the first run with `utils.SetStatusCallback(status);` commenting it out, Unity crashed on the second one?

**Comment by nxrighthere** [comment]
@mnursey If after the first run with `utils.SetStatusCallback(status);` commenting it out, Unity crashes on the second one?

**Comment by mnursey** [comment]
If I comment it out it does not crash.

**Comment by fletcherdvalve** [comment]
If you share the .pdbs, we might be able to offer some more analysis.  Right now, without symbols, I can't see the callstack.  Do you know if it is the ConnectionStatusChangedCallback callback, or the debug output callback?

If SetDebugOutputFunction callback is set, then that code segment needs to stay viable for the lifetime of the SteamNetworkingSockets library.  I had a bug in Source2 code similar to this briefly.  We were installing a debug callback that pointed to a function in a .dll.  And then we were unloading that .dll before terminating this library.  That will produce a crash very similar to this.

**Comment by nxrighthere** [comment]
@fletcherdvalve It's `ConnectionStatusChangedCallback`, from his Unity logs. The crash occurs at `SteamAPI_ISteamNetworkingSockets_RunCallbacks()` call, I'm not sure if it's possible to dive deeper in this case.

**Comment by nxrighthere** [comment]
@mnursey Is crash occurs without `utils.SetDebugCallback(DebugType.Message, debug);`?

**Comment by nxrighthere** [comment]
@mnursey Does the crash occurs without utils.SetDebugCallback(DebugType.Message, debug);?

**Comment by nxrighthere** [comment]
@mnursey Does the crash occurs without `utils.SetDebugCallback(DebugType.Message, debug);`?

**Comment by fletcherdvalve** [comment]
Oh I see the log actually has a call stack in there.  It's interesting that it knows the managed functions on the stack, but no native functions.

```
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 0000000000000246)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 0000000000000246)
0x0000000000000246 ((<unknown>)) (function-name not available)
0x0000020B5FB39E93 (mscorlib) System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize()
0x0000020B5FBB3E5B (Assembly-CSharp) Valve.Sockets.NetworkingSockets.RunCallbacks()
0x0000020B5FBB3ACB (Assembly-CSharp) ClientController.Receive()
```

It makes me wonder if the problem is the call into the RunCallbacks() function, or if the bad jump is a status callback itself.  I'm guessing it's actually the former.  In other words, this would crash even if no connections were ever made or ever changed state and queued callbacks.

What is the lifetime of the C# ``NetworkingSockets`` object?  If you kill the library and re-initialize, you will need to create a new instance of this object.

**Comment by nxrighthere** [comment]
`NetworkingSockets` re-created at the second run, I feel like there's an invalid pointer somewhere/somehow from the previous run since unmanaged memory never unloaded in Unity with native plugins.

**Comment by fletcherdvalve** [comment]
This is an order of operations bug.

```

public void ConnectToServer(...) {
    utils = new NetworkingUtils();
    utils.SetDebugCallback(DebugType.Message, debug);

    client = new NetworkingSockets();

    Address address = new Address();

    address.SetAddress(serverIP, serverport);

    connection = client.Connect(ref address);

    status = OnClientStatusUpdate;
    utils.SetStatusCallback(status);
}

```

The problem is that the client.Connect() call will cause a status callback to be queued.  But it is queued using the currently registered callback function, which is set to the delegate from the previous run, which which has been destroyed.

Setting the callback before the connect call will probably fix the problem.

Leaving a callback installed after the delegate is destroyed is really the problem here.   I'm not sure if the best place for this to be fixed is in the native level, the C# layer, or the application.

**Comment by mnursey** [comment]
Updating the ordering fixes the issue. Unity does not crash anymore. Should there be a warning for this kind of behavior?

Thank you both for all the help. It's much appreciated.

Should I close the issue?

**Comment by nxrighthere** [comment]
@fletcherdvalve The way I can solve that in C# is to use [disposable pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose) with `IDisposal` interface for `NetworkingUtils` class so the callback will reset at the object disposal.

**Comment by fletcherdvalve** [comment]
@nxrighthere That sounds good, if there is something that doesn't have any surprises or downsides.  I have thought about clearing the callbacks at certain times, but it's not an unambiguous win.
