### ISSUE TITLE
steamnetworkingsockets really really slow

### ISSUE THREAD

**Issue by Milk-Drinker01** [nxrighthere/ValveSockets-CSharp#15]
Hi, i am going to start by saying that i am using facepunch.steamworks for sockets, not this. However, im considering the switch to this for one reason, and im wondering if something is wrong. I implimented my own netcode using system.net.sockets, with tcp and udp support. I didnt want players to have to port forward to play with one another, so i implimented steam networking sockets, sending reliable packets to replace tcp and unreliable packets to replace udp (makes sense, right?). the issue that im having is that vs my own solution, my game is so slow its unplayable. the ping is just super high for clients, like 240 from USE to UK. I did some testing with a ping pong packet, and it turns out that both unreliable and reliable messages have the exact same ping time, which doesnt make sense to me. what is the point of an unreliable packet if its the same speed as a reliable one? is this an issue with facepunch.steamworks? what kind of performance do you get using steamnetworkingsockets?

**Comment by nxrighthere** [comment]
Please, use the [appropriate repository](https://github.com/ValveSoftware/GameNetworkingSockets) for technical questions that related to the GameNetworkingSockets library itself. This repository only provides a wrapper of native API.
