### ISSUE TITLE
Application didn't accept or close incoming connection in a reasonable amount of time

### ISSUE THREAD

**Issue by tuddor1234** [nxrighthere/ValveSockets-CSharp#18]
Hey. I am trying to include this Wrapper into my Unity Projects and as soon as I tried to connect to the server, I get the following messages: 

Debug - Type: Bug, Message: E:\Extra\Tudor\Projects\MobileController\GameSockets\GameNetworkingSockets-1.2.0\vcpkg\buildtrees\gamenetworkingsockets\src\7a54b1e6c2-a58e0d55db.clean\src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp(3267): Application didn't accept or close incoming connection in a reasonable amount of time.  This is probably a bug.
UnityEngine.MonoBehaviour:print (object)
Server/<>c:<Start>b__7_1 (Valve.Sockets.DebugType,string) (at Assets/Server.cs:53) 

Debug - Type: Message, Message: [#2350480830 UDP [::1]:57469] problem detected locally (5003): App didn't accept or close incoming connection in time.
UnityEngine.MonoBehaviour:print (object)
Server/<>c:<Start>b__7_1 (Valve.Sockets.DebugType,string) (at Assets/Server.cs:53)

Debug - Type: Bug, Message: [#2350480830 UDP [::1]:57469] We are in state 5 and have been waiting 20.0s to be cleaned up.  Did you forget to call CloseConnection()?
UnityEngine.MonoBehaviour:print (object)
Server/<>c:<Start>b__7_1 (Valve.Sockets.DebugType,string) (at Assets/Server.cs:53)

Do you have any idea how to solve this?

I have attached the source code for both the client and server.
[client.docx](https://github.com/nxrighthere/ValveSockets-CSharp/files/7355361/client.docx)
[server.docx](https://github.com/nxrighthere/ValveSockets-CSharp/files/7355362/server.docx)
 
P.S. The two project are running on the same machine.

**Comment by fletcherdvalve** [comment]
This output means there is probably a bug in the *application*.  There was a connection that came into the server, and the server didn't do anything with it in a reasonable amount of time.  It should either accept the connection or close it.  I doubt (but am not 100% certain) that the wrapper is not designed to take care of this, either.

**Comment by nxrighthere** [comment]
What version of the native library do you use? Do you keep Unity [run in the background](https://docs.unity3d.com/ScriptReference/Application-runInBackground.html) when the application loses focus?

**Comment by ifshuaishuai** [comment]
After some digging, C# wrapper(ValveSockets-CSharp) must match GameNetworkingSockets's version, now is 1.2.0. So download 1.2.0 version on release page.
