### ISSUE TITLE
Wrapper is broken after library got updated

### ISSUE THREAD

**Issue by Damianu** [nxrighthere/ValveSockets-CSharp#2]
This commit changed CreateListenSocket to CreateListenSocketIp with different params
https://github.com/ValveSoftware/GameNetworkingSockets/commit/d07b7b2edaac432a99bf157bcd9a7a0abc721402

**Comment by nxrighthere** [comment]
Yes, I saw that they updated the library, I'm just waiting until they release it since it's still subject to change.

**Comment by Damianu** [comment]
Trying to build it with older version of repo gets me through server setup... however when I am trying to make client it crashes:
```The program '[13836] dotnet.exe' has exited with code -1073740940 (0xc0000374).```
on line:
```
client.Connect("127.0.0.1", 7777);
```

**Comment by nxrighthere** [comment]
Make sure that all required dependencies are placed in the same folder with the native library.

**Comment by Damianu** [comment]
Added OpenSSL dlls (thought it would be enough to have them on windows level, turns out it isnt) and it fixed the issue, however now I get:
```
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
```
Can you please tell me on which commit did you build your GameNetworkingSockets.dll? (Or I'd really aprettiate sending already built dll that works with this wrapper)

**Comment by nxrighthere** [comment]
This version works without any issues on my side. All required dependencies are included, but you need to change locations with CMake.

[GameNetworkingSockets.zip](https://github.com/nxrighthere/ValveSockets-CSharp/files/2746656/GameNetworkingSockets.zip)

**Comment by nxrighthere** [comment]
Forgot to mention that I'm using MinGW for building.

**Comment by nxrighthere** [comment]
The wrapper updated to the latest version up to https://github.com/ValveSoftware/GameNetworkingSockets/commit/c4a97732fd6cad7f146d51a6f674ab705719f4d0 commit. API reference is under construction.

**Comment by nxrighthere** [comment]
Updated to the latest version up to https://github.com/ValveSoftware/GameNetworkingSockets/commit/1f90ef7548dfee30476a592398dfc325fc57b6f2 commit. API reference update in progress.

**Comment by fletcherdvalve** [comment]
Thanks.  trying really hard to to avoid making any more changes to the API before 1.0 is released!

**Comment by nxrighthere** [comment]
Feel free to make any changes, I'll adapt. 😸

**Comment by nxrighthere** [comment]
@fletcherdvalve Fletch, did you receive my mail 8 days ago?

**Comment by fletcherdvalve** [comment]
Sorry haven't had a chance to look at it.  But I will!
When I look at perf.  Right now perf I think is OK for v1, I just need to ship, so trying to focus

**Comment by nxrighthere** [comment]
Sure, the link to files expired there so drop me a message if you want me to send it again.

**Comment by nxrighthere** [comment]
Updated to the latest version up to https://github.com/ValveSoftware/GameNetworkingSockets/commit/53db7d349c15ee3b208eda46bffe674267e90fac commit.

**Comment by nxrighthere** [comment]
The wrapper updated to the latest 1.0.0 version.
