### ISSUE TITLE
IL2CPP support

### ISSUE THREAD

**Issue by sebas77** [nxrighthere/ValveSockets-CSharp#20]
it seems that this code doesn't support unity IL2CPP because of 

_: IL2CPP does not support marshaling delegates that point to instance methods to native code_

do you have any suggestions about it?

**Comment by nxrighthere** [comment]
I'm not using Unity for about two years, and I'm not familiar with this limitation, sorry.

**Comment by ifshuaishuai** [comment]
You can fix this with simple solution:

**[MonoPInvokeCallback(typeof(StatusCallback))]**
**static** void OnClientStatusUpdate(ref StatusInfo info)
{
...
}
