### ISSUE TITLE
Unity crash !

### ISSUE THREAD

**Issue by ziiCz** [nxrighthere/ValveSockets-CSharp#5]
Hello!

When I try to connect the client with the client.Connect() function, Unity crash without error message. I have no problem when I start the server. This problem only appears for the client connection. Do you have this problem too? If yes or if you already had it, do you know how to solve it?

Thank you in advance.

**Comment by nxrighthere** [comment]
I'm unable to reproduce this. You are using the latest version of the native library from master or from the release section?

**Comment by nxrighthere** [comment]
I made tiny improvements that potentially could solve this if you are using IL2CPP, but I don't have any issues with the 1.0.0 version downloaded from the release section.

**Comment by nxrighthere** [comment]
Here's a simple chat example created by some nice guy https://github.com/DylanYasen/unity-ValveGameNetworkingSockets-chat-example

**Comment by DylanYasen** [comment]
omg senpai. I'm honored.

**Comment by ziiCz** [comment]
Ok men I will try this chat example. Especially if it's done by nice guys :)
Thank for your answers !
