### ISSUE TITLE
Handling case k_ESteamNetworkingConnectionState_ProblemDetectedLocally: is missing

### ISSUE THREAD

**Issue by Levendo** [nxrighthere/ValveSockets-CSharp#7]
Hey,

Thanks for the binding class of GNS. It is helpful.

What i noticed is, case " k_ESteamNetworkingConnectionState_ProblemDetectedLocally:" is not handled on below sample server application. 

```
StatusCallback status = (info, context) => {
	switch (info.connectionInfo.state) {
		case ConnectionState.None:
			break;

		case ConnectionState.Connecting:
			server.AcceptConnection(info.connection);
			server.SetConnectionPollGroup(pollGroup, info.connection);
			break;

		case ConnectionState.Connected:
			Console.WriteLine("Client connected - ID: " + info.connection + ", IP: " + info.connectionInfo.address.GetIP());
			break;

		case ConnectionState.ClosedByPeer:
			server.CloseConnection(info.connection);
			Console.WriteLine("Client disconnected - ID: " + info.connection + ", IP: " + info.connectionInfo.address.GetIP());
			break;
	}
};
```

So disconnected client resources on native side not removed (by not calling CloseConnection()). 

That can be problematic when you have good amount of connect/disconnect use cases. like 16k clients connected to server for some time interval. After a while a new client becomes unable to connect, because of the duplicate data on containers on native side.

 I address the problem at [this issue](https://github.com/ValveSoftware/GameNetworkingSockets/issues/96) and it is discovered that it is the binding class is missing the handling "k_ESteamNetworkingConnectionState_ProblemDetectedLocally".

So better to have case ConnectionState.ProblemDetectedLocally: to free the resources as below:

```
StatusCallback status = (info, context) => {
	switch (info.connectionInfo.state) {
		case ConnectionState.None:
			break;

		case ConnectionState.Connecting:
			server.AcceptConnection(info.connection);
			server.SetConnectionPollGroup(pollGroup, info.connection);
			break;

		case ConnectionState.Connected:
			Console.WriteLine("Client connected - ID: " + info.connection + ", IP: " + info.connectionInfo.address.GetIP());
			break;

		case ConnectionState.ClosedByPeer:
                case ConnectionState.ProblemDetectedLocally:
			server.CloseConnection(info.connection);
			Console.WriteLine("Client disconnected - ID: " + info.connection + ", IP: " + info.connectionInfo.address.GetIP());
			break;
	}
};
```

**Comment by nxrighthere** [comment]
The [documentation](https://github.com/nxrighthere/ValveSockets-CSharp#connectionstate) clearly states:
> `ConnectionState.ProblemDetectedLocally` a disruption in the connection has been detected locally. Attempts to send further messages will fail. Any remaining received messages in the queue are available. The connection still exists from an API perspective and must be closed to free up resources.

I've fixed the example in the readme, thanks.
