### ISSUE TITLE
No socket activity

### ISSUE THREAD

**Issue by ZeroByter** [nxrighthere/ValveSockets-CSharp#9]
Hey so I tried copying your server/client example code and putting it in my project for testing but when I launch two Unity instances and connecting to each it nothing happens. There are no logs of anything happening.

Strangely, after a few seconds the StatusCallback loop (inside an Update function) returns '-1 messages'.

There are no errors or anything, I remembered to initialize the ValveSockets and all.

I tested the `.dll` compiled dll with the chat example and that works, so I guess I am somehow using this CSharp wrapper wrong. No clue.

**Comment by ZeroByter** [comment]
Nevermind it was outputting stuff but I wasn't seeing it cause Unity wasn't outputting it initially at first, whatever.

**Comment by nxrighthere** [comment]
> Usage is almost the same as in the .NET environment, except that the console functions must be replaced with functions provided by Unity.
